# projeto do arquivo do wokflow do git 
name: TI222

on:
  push:
    branches: [ main, dev]
  
  workflow_dispatch:
    inputs: 
        enviroment:
          description: Ambientes
          type: choice
          required: true
          default: dev
          options:
            - dev
            - main

jobs:
  informacao:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar a estrutura de diretorio
        run: ls -la
      - name: Obtem codigo do projeto do repositorio
        uses: actions/checkout@v3
      - name: Mostrar a estrutura de diretorio atualizada
        run: |
          echo "Estrutura do repositorio : "
          ls -la
          echo "exemplo de listar um diretorio "
          ls -la api || echo "Nao existe o diretorio"
      - name: Gera saida do github context sem execucao direta
        run: |
          echo 'Github Context:'> github_context.txt
          echo '${{ toJSON(github) }}' .. github_context.txt
          cat github_context.txt
              
  
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /  # define o diretorio base 

    steps:
      - name: checkout Code
        uses: actions/checkout@v3    

      # ftp para o site https://www.sergio.dev.br/engsis
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          #local-dir: /
          #server-dir: /
          port: 21
          protocol: FTP
          log-level: verbose  